name: Build and Push to Artifact Registry

on:
  push:
    branches:
    - 'main'
env:
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  IMAGE_NAME: ${{ github.repository }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2  # Adjust version as needed
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GOOGLE_PROJECT }}

    - name: build and push the docker image
 
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/${{ env.GOOGLE_PROJECT }}/appointment-api/${{ env.IMAGE_NAME }}:latest .
        docker push us-central1-docker.pkg.dev/${{ env.GOOGLE_PROJECT }}/appointment-api/${{ env.IMAGE_NAME }}:latest
