
name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
    
env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/appointment-api/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
            credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag appointment:latest  
        working-directory: .

      - name: Push image
        run: docker push appointment:latest 
